# ---------------------------------------------------------------------------- #
# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# SPDX-License-Identifier: MIT-0
#
# Streaming and configuration types shared by all the agent implementations
# ---------------------------------------------------------------------------- #
from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, model_validator


class EStreamEvent(Enum):
    """Defines the possible stream event types for streaming operations.

    Attributes:
        STREAM_COMPLETE: Event indicating that the stream has completed
        THINKING_TOKEN: Event indicating that the model is processing/thinking
        FINAL_RESPONSE_TOKEN: Event indicating a token from the final response
    """

    STREAM_COMPLETE = "STREAM_COMPLETE"
    THINKING_TOKEN = "THINKING_TOKEN"  # nosec B105
    FINAL_RESPONSE_TOKEN = "FINAL_RESPONSE_TOKEN"  # nosec B105


class EConversationManagerType(str, Enum):
    """Defines the possible conversation manager types for handling chat history.

    Attributes:
        NULL: No conversation management - each message is handled independently
        SLIDING_WINDOW: Maintains a sliding window of recent messages for context
        SUMMARIZING: Summarizes older messages to maintain context while managing memory
    """

    NULL = "null"
    SLIDING_WINDOW = "sliding_window"
    SUMMARIZING = "summarizing"


class StrandToken(BaseModel):
    """Represents a token generated by Strands Agents with associated event flag.

    Attributes:
        value (str): The text value of the token
        flag (EStreamEvent): The event flag associated with this token.
            See `EStreamEvent` for valid options.
    """

    value: str
    flag: EStreamEvent


class InferenceConfig(BaseModel):
    """Configuration for model inference parameters.

    Attributes:
        maxTokens (int): Maximum number of tokens to generate in the response
        temperature (float): Controls randomness in response generation. Higher values (e.g. 1.0) make output more random,
            lower values (e.g. 0.1) make it more focused and deterministic
        stopSequences (Optional[List[str]]): List of sequences that will stop text generation when encountered. Default None
    """

    maxTokens: int
    temperature: float
    stopSequences: Optional[list[str]] = None


class ReasoningEffort(str, Enum):
    """Reasoning effort level.

    ``NONE`` explicitly disables reasoning and is distinct from
    ``reasoningBudget=None``, which omits the parameter entirely. The
    distinction matters for always-on models (Grok 4.3, GPT-5.6): omitting the
    field still yields reasoning, so ``none`` must be sent to silence them.

    Not every model accepts every level — see ``REASONING_CAPABILITIES``.
    """

    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    XHIGH = "xhigh"
    MAX = "max"


class ReasoningCapability(BaseModel):
    """What reasoning controls one model family accepts.

    Attributes:
        efforts (frozenset[ReasoningEffort]): Effort values the model accepts. A
            value outside this set is rejected at config-parse time rather than
            surfacing as a provider 400 at first inference.
        can_disable (bool): Whether reasoning can be turned off at all. False
            for models whose card states reasoning is always active
            (``claude-sonnet-5``, ``xai.grok-4.3`` reasons unless explicitly set
            to ``none``). When False, ``ReasoningEffort.NONE`` must not appear in
            ``efforts``.
        default_effort (Optional[ReasoningEffort]): The effort the provider
            applies when the parameter is omitted, **only where AWS documents
            it**. None means the default is genuinely undocumented (the
            ``openai.*`` families publish accepted values but never a default).
            Consumed by the UI to prefill the effort picker; never substituted
            into a request when the user left the field unset.
        recommended_effort (Optional[ReasoningEffort]): A card-recommended value
            that is *not* the provider default. Kept distinct from
            ``default_effort`` so the UI can say "recommended" without claiming
            it is what the provider would do.
    """

    efforts: frozenset[ReasoningEffort]
    can_disable: bool
    default_effort: Optional[ReasoningEffort] = None
    recommended_effort: Optional[ReasoningEffort] = None


_EFFORT_LMH = frozenset(
    {ReasoningEffort.LOW, ReasoningEffort.MEDIUM, ReasoningEffort.HIGH}
)
# Anthropic adaptive thinking: the full ladder minus ``none`` (the Messages API
# rejects it — "unknown variant `none`, expected one of `low`, `medium`, `high`,
# `xhigh`, `max`", which is the authoritative enum). Applies to Sonnet as well as
# Opus: the Bedrock adaptive-thinking page calls xhigh/max "Opus only", but
# claude-sonnet-5 accepts both (verified live 2026-07-29).
_EFFORT_ANTHROPIC = _EFFORT_LMH | {ReasoningEffort.XHIGH, ReasoningEffort.MAX}
# The five levels most OpenAI-surface families accept: everything except ``max``.
_EFFORT_NO_MAX = _EFFORT_LMH | {ReasoningEffort.NONE, ReasoningEffort.XHIGH}
# GPT-5.6 (Sol/Terra/Luna) is the only family that accepts all six.
_EFFORT_ALL = _EFFORT_NO_MAX | {ReasoningEffort.MAX}
# Nova 2 on Converse: only low/medium are usable as-is. ``high`` is accepted by
# the model but requires ``maxTokens`` to be unset, which ``create_model``
# handles by dropping it (see base_factory). ``none``/``xhigh``/``max`` are not
# in Nova's enum at all.
_EFFORT_NOVA = frozenset(
    {ReasoningEffort.LOW, ReasoningEffort.MEDIUM, ReasoningEffort.HIGH}
)


# Model-id fragment -> reasoning capability. Keyed by fragment (substring match)
# so one entry covers a family and both the geo-prefixed and unprefixed forms of
# the same id (``us.amazon.nova-2-lite-v1:0`` / ``amazon.nova-2-lite-v1:0``).
#
# PROVENANCE: the accepted-effort sets are **empirically verified**, not taken
# from the docs. A live enumeration in us-east-1 (2026-07-29 — every effort value
# against every family, `cache/t4_enumerate.py`) found the AWS model cards and the
# adaptive-thinking page wrong or incomplete for 7 of 12 families, always in the
# too-strict direction. Where the two disagree, the live result wins. Notably:
#   * xhigh/max are NOT Opus-only — claude-sonnet-5 takes both.
#   * gpt-5.4/5.5 take none+xhigh (but reject max); only 5.6 takes all six.
#   * gemma-4-* and grok-4.3 take none+xhigh, undocumented on their cards.
#   * gpt-oss reasons at all, which its card omits entirely.
# Re-run that script when adding a family rather than trusting a card.
#
# NOT discoverable at runtime — the Mantle ``/v1/models`` catalog exposes no
# reasoning metadata (only id, created, object, owned_by, data_retention,
# status). Same necessity as ``_MANTLE_OPENAI_V1_CHAT_PREFIXES`` in
# base_factory.py. Re-check the cards
# when adding a model to the region catalog (iac-cdk/lib/shared/supported-
# models.ts). Mirrored in the frontend as REASONING_CAPABILITIES in
# wizard-utils.ts; tests assert the two agree.
#
# Deliberately absent: qwen3-* report "Reasoning: Supported" but the control is
# a ``/no_think`` token appended to the prompt, with no API parameter — an
# effort level there would be silently ignored. Also absent: every model whose
# card carries no Reasoning field (deepseek.v3.2, minimax, kimi-k2.5, nemotron,
# glm-*, mistral/ministral, gemma-3-*, nova-2-sonic).
REASONING_CAPABILITIES: dict[str, ReasoningCapability] = {
    # -- Anthropic (Messages on Mantle / Converse) ---------------------------
    # Adaptive thinking: `thinking={"type": "adaptive"}` + output_config.effort.
    # `high` is the documented default ("At the default effort level (high),
    # Claude will almost always think").
    "claude-opus-5": ReasoningCapability(
        efforts=_EFFORT_ANTHROPIC,
        can_disable=True,
        default_effort=ReasoningEffort.HIGH,
    ),
    "claude-opus-4-8": ReasoningCapability(
        efforts=_EFFORT_ANTHROPIC,
        can_disable=True,
        default_effort=ReasoningEffort.HIGH,
    ),
    "claude-opus-4-6": ReasoningCapability(
        efforts=_EFFORT_ANTHROPIC,
        can_disable=True,
        default_effort=ReasoningEffort.HIGH,
    ),
    # Sonnet takes the same five levels as Opus, contra the adaptive-thinking
    # page's "Opus only" claim about xhigh/max (verified live). Sonnet 5's card
    # states thinking is always on and cannot be disabled, so `can_disable` is
    # False — consistent with the Messages API rejecting `none` outright.
    "claude-sonnet-5": ReasoningCapability(
        efforts=_EFFORT_ANTHROPIC,
        can_disable=False,
        default_effort=ReasoningEffort.HIGH,
    ),
    "claude-sonnet-4-6": ReasoningCapability(
        efforts=_EFFORT_ANTHROPIC,
        can_disable=True,
        default_effort=ReasoningEffort.HIGH,
    ),
    # -- OpenAI proprietary (Responses on /openai/v1) -----------------------
    # "gpt-5." is a prefix of "gpt-5.6", so the lookup's longest-match is what
    # keeps `max` from leaking to 5.4/5.5 — they accept none+xhigh but 400 on
    # `max` ("not supported with the 'openai.gpt-5.5' model").
    "gpt-5.6": ReasoningCapability(efforts=_EFFORT_ALL, can_disable=True),
    "gpt-5.5": ReasoningCapability(efforts=_EFFORT_NO_MAX, can_disable=True),
    "gpt-5.4": ReasoningCapability(efforts=_EFFORT_NO_MAX, can_disable=True),
    # -- OpenAI open-weights (Chat Completions on /v1) ----------------------
    # The gpt-oss cards carry no Reasoning field at all; support is documented
    # only in the AWS GovCloud launch blog, and confirmed live. Genuinely
    # three-level: none/xhigh/max all 400.
    "gpt-oss": ReasoningCapability(efforts=_EFFORT_LMH, can_disable=True),
    # -- Google Gemma 4 (Chat Completions on /openai/v1) --------------------
    # Reasoning is listed in the card's bedrock-mantle feature table; the
    # none+xhigh support below is undocumented and live-verified.
    "gemma-4-31b": ReasoningCapability(efforts=_EFFORT_NO_MAX, can_disable=True),
    "gemma-4-26b-a4b": ReasoningCapability(efforts=_EFFORT_NO_MAX, can_disable=True),
    # E2B over-reasons by default; the card *recommends* high to keep the
    # reasoning in its own channel. A recommendation, not the provider default.
    "gemma-4-e2b": ReasoningCapability(
        efforts=_EFFORT_NO_MAX,
        can_disable=True,
        recommended_effort=ReasoningEffort.HIGH,
    ),
    # -- xAI (Chat Completions on /openai/v1) -------------------------------
    # "Reasoning is always active by default"; `none` is the only way off, and
    # `low` is the documented default. `xhigh` is accepted but undocumented.
    "grok-4.3": ReasoningCapability(
        efforts=_EFFORT_NO_MAX,
        can_disable=True,
        default_effort=ReasoningEffort.LOW,
    ),
    # -- Amazon Nova (Converse) ---------------------------------------------
    # reasoningConfig={"type": "enabled", "maxReasoningEffort": ...}. Off by
    # default, so there is no default effort to report. `high` additionally
    # requires maxTokens to be unset — create_model drops it (see base_factory).
    # `none`/`xhigh`/`max` are not in Nova's enum.
    "nova-2-lite": ReasoningCapability(efforts=_EFFORT_NOVA, can_disable=True),
}


def reasoning_capability_for(model_id: str) -> Optional[ReasoningCapability]:
    """Return the reasoning capability for ``model_id``, or None if unsupported.

    Matches the **longest** ``REASONING_CAPABILITIES`` fragment contained in
    ``model_id`` so a specific family entry beats a shorter prefix of itself:
    ``"gpt-5.6-luna"`` contains both ``"gpt-5.6"`` and (via the shared prefix)
    would match a hypothetical ``"gpt-5."`` entry, and the six-level set must
    win. A ``None`` return means the model exposes no controllable reasoning —
    callers must reject a reasoning budget rather than silently dropping it.

    Args:
        model_id (str): Model id as configured, verbatim — either a Mantle short
            id (``"anthropic.claude-opus-4-8"``) or a Converse/inference-profile
            form (``"us.amazon.nova-2-lite-v1:0"``).

    Returns:
        Optional[ReasoningCapability]: The capability, or None when the model
            exposes no reasoning parameter.
    """
    matches = [frag for frag in REASONING_CAPABILITIES if frag in model_id]
    if not matches:
        return None
    return REASONING_CAPABILITIES[max(matches, key=len)]


class ModelConfiguration(BaseModel):
    """Configuration class for model inference settings.

    Attributes:
        modelId (str): Identifier for the model to be used
        parameters (InferenceConfig): Configuration parameters for model inference
        reasoningBudget (Optional[ReasoningEffort]): Reasoning effort level for
            reasoning-capable models, validated per model against
            ``REASONING_CAPABILITIES``. Default None, meaning the parameter is
            omitted entirely — note that always-on models still reason when it
            is omitted; use ``ReasoningEffort.NONE`` to disable explicitly.
    """

    modelId: str
    parameters: InferenceConfig
    reasoningBudget: Optional[ReasoningEffort] = None

    @model_validator(mode="after")
    def validate_reasoning_budget(self) -> "ModelConfiguration":
        """Reject a reasoning budget the model does not accept.

        Two failure modes with distinct messages: the model exposes no reasoning
        parameter at all, or it reasons but not at the requested effort level
        (that message names the accepted set so the caller can self-correct).

        Raises:
            ValueError: On either failure mode.
        """
        if self.reasoningBudget is None:
            return self

        capability = reasoning_capability_for(self.modelId)
        if capability is None:
            raise ValueError(
                f"reasoningBudget is not supported for model '{self.modelId}'"
            )

        if self.reasoningBudget not in capability.efforts:
            accepted = ", ".join(
                effort.value
                for effort in ReasoningEffort
                if effort in capability.efforts
            )
            raise ValueError(
                f"reasoningBudget '{self.reasoningBudget.value}' is not accepted "
                f"for model '{self.modelId}'. Accepted values: {accepted}."
            )

        return self


class Token(BaseModel):
    """Represents a token with its position in the sequence.

    Attributes:
        position (int): The position of the token in the sequence
        value (str): The text value of the token
    """

    position: int
    value: str


class ChatbotAction(Enum):
    """
    Enum class defining the possible actions that can be taken by the chatbot.

    Attributes:
        HEARTBEAT: Represents a heartbeat action to check if the chatbot is active
        RUN: Represents the main execution action of the chatbot
        ON_THINKING_TOKEN: Represents a thinking token action while the chatbot processes
        ON_NEW_LLM_TOKEN: Represents a new token received from the language model that belongs to the final answer
        FINAL_RESPONSE: Represents the final response action from the chatbot
    """

    HEARTBEAT = "heartbeat"
    RUN = "run"
    ON_THINKING_TOKEN = "on_thinking_token"  # nosec B105
    ON_NEW_LLM_TOKEN = "on_new_llm_token"  # nosec B105
    FINAL_RESPONSE = "final_response"
