# ---------------------------------------------------------------------------- #
# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# SPDX-License-Identifier: MIT-0
# ---------------------------------------------------------------------------- #
from __future__ import annotations

from typing import TYPE_CHECKING

from shared.base_callbacks import BaseAgentCallbacks
from strands.hooks import AfterToolCallEvent, BeforeToolCallEvent

if TYPE_CHECKING:
    from logging import Logger


class AgentCallbacks(BaseAgentCallbacks):
    """Class to handle callbacks for swarm agent operations.

    This class extends BaseAgentCallbacks for swarm agent operations including
    tool invocations and knowledge base retrievals. It manages metadata collection
    and logging during swarm execution.

    Attributes:
        _metadata (dict): Dictionary storing metadata generated by tools, e.g. Knowledge base references.
        _logger (Logger): Logger instance for recording agent operations and tool usage.
        _tool_executions (dict): Maps tool_call_id to its invocationNumber so
            log_tool_results can emit a correlated tool_complete. Swarm agents
            share a single CALLBACKS instance, so invocation numbers stay globally
            unique per turn even across hand-offs.
    """

    def __init__(self, logger: Logger, session_id: str, user_id: str) -> None:
        super().__init__(logger, session_id, user_id)
        self._tool_executions: dict[str, dict] = {}

    def reset_metadata(self) -> None:
        """Reset metadata, tool invocation counter, and tool executions."""
        super().reset_metadata()
        self._tool_executions = {}

    def log_tool_entries(self, event: BeforeToolCallEvent) -> None:
        """Logs information about tool invocation before it occurs.

        Args:
            event (BeforeToolCallEvent): Event containing metadata about the tool
                that will be invoked.

        Returns:
            None
        """
        specs = event.selected_tool.tool_spec if event.selected_tool else None

        self._nb_tool_invocations += 1

        self._logger.info(
            f"Agent is going to call tool #{self._nb_tool_invocations} in this turn",
            extra={"toolSpecifications": specs, "toolParameters": event.tool_use},
        )

        # Track invocationNumber by tool_call_id so log_tool_results can emit a
        # correlated tool_complete (after_tool does not increment the counter).
        tool_call_id = event.tool_use.get("toolUseId", "")
        if tool_call_id:
            self._tool_executions[tool_call_id] = {
                "invocationNumber": self._nb_tool_invocations,
            }

        # Extract parameters using base class helper
        parameters = self._extract_tool_parameters(event, specs)

        tool_name = event.tool_use.get("name", "unknown")
        tool_description = specs.get("description", "") if specs else ""

        # Send tool action directly via WebSocket for instant UI feedback
        self._send_tool_action(tool_name, tool_description, parameters)

    def log_tool_results(self, event: AfterToolCallEvent) -> None:
        """Logs tool results after tool execution.

        Args:
            event (AfterToolCallEvent): Event containing tool results.
        """
        if event.selected_tool:
            tool_name = event.selected_tool.tool_name

            self._logger.info(
                "The tool returned a response",
                extra={
                    "payload": {
                        "toolName": tool_name,
                        "result": event.result,
                    }
                },
            )

            # Notify the UI the tool finished, correlated via invocationNumber.
            tool_call_id = (
                event.tool_use.get("toolUseId", "")
                if hasattr(event, "tool_use") and event.tool_use
                else ""
            )
            invocation_number = (
                self._tool_executions.get(tool_call_id, {}).get("invocationNumber")
                if tool_call_id
                else None
            )
            if invocation_number is not None:
                self._send_tool_complete(
                    tool_name,
                    invocation_number,
                    self._tool_status_from_result(event.result),
                )
